### 다중선형회귀
* 시간대비 성적데이터를 좀 더 정확한 예측을 위해서는 추가정보 필요
* 공부시간외에 성적에 영향을 끼칠수 있는 다른 요인필요
* 과외시간을 추가함 => 항이 추가 => 기울기 하나 더 추가

In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import RMSprop

In [2]:
times = [2,4,6,8]
lession= [0,4,2,3]
sungjuk = [81,93,91,97]

In [3]:
data = [[2,0,81],[4,4,93],[6,2,91],[8,3,97]]
xdata1 = [x[0] for x in data]
xdata2 = [x[1] for x in data]
ydata = [x[2] for x in data]

In [4]:
a = tf.Variable(tf.random_uniform([1], 0, 10,
                dtype=tf.float64, seed=1))
b = tf.Variable(tf.random_uniform([1], 0, 10,
                dtype=tf.float64, seed=1))
c = tf.Variable(tf.random_uniform([1], 0, 100,
                dtype=tf.float64, seed=1))

In [5]:
y = a * xdata1 + b * xdata2 + c

In [6]:
rmse = tf.sqrt(tf.reduce_mean(tf.square(y - ydata)))

In [7]:
learn_rate = 0.1

In [8]:
gradient_decent = tf.train.GradientDescentOptimizer\
                (learn_rate).minimize(rmse)

In [9]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        sess.run(gradient_decent)
        if step % 10 == 0:
            print('훈련횟수 epoch %.f, RMSE %.3f,'\
            '기울기1 %.3f, 기울기2 %.3f, 절편 %.3f' %
                  ( step, sess.run(rmse),
                    sess.run(a), sess.run(b),
                    sess.run(c) ))

2021-12-03 11:15:06.024365: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA


훈련횟수 epoch 0, RMSE 67.394,기울기1 8.582, 기울기2 8.871, 절편 91.136
훈련횟수 epoch 10, RMSE 31.201,기울기1 3.204, 기울기2 6.344, 절편 90.187
훈련횟수 epoch 20, RMSE 5.508,기울기1 -1.120, 기울기2 4.052, 절편 89.288
훈련횟수 epoch 30, RMSE 5.025,기울기1 -0.919, 기울기2 3.503, 절편 88.941
훈련횟수 epoch 40, RMSE 4.666,기울기1 -0.670, 기울기2 3.084, 절편 88.590
훈련횟수 epoch 50, RMSE 4.378,기울기1 -0.458, 기울기2 2.753, 절편 88.225
훈련횟수 epoch 60, RMSE 4.142,기울기1 -0.280, 기울기2 2.500, 절편 87.850
훈련횟수 epoch 70, RMSE 3.939,기울기1 -0.131, 기울기2 2.313, 절편 87.468
훈련횟수 epoch 80, RMSE 3.757,기울기1 -0.006, 기울기2 2.179, 절편 87.082
훈련횟수 epoch 90, RMSE 3.586,기울기1 0.102, 기울기2 2.087, 절편 86.693
훈련횟수 epoch 100, RMSE 3.421,기울기1 0.195, 기울기2 2.027, 절편 86.303
훈련횟수 epoch 110, RMSE 3.261,기울기1 0.277, 기울기2 1.991, 절편 85.912
훈련횟수 epoch 120, RMSE 3.101,기울기1 0.352, 기울기2 1.972, 절편 85.520
훈련횟수 epoch 130, RMSE 2.943,기울기1 0.420, 기울기2 1.965, 절편 85.129
훈련횟수 epoch 140, RMSE 2.786,기울기1 0.485, 기울기2 1.968, 절편 84.737
훈련횟수 epoch 150, RMSE 2.629,기울기1 0.547, 기울기2 1.976, 절편 84.346
훈련횟수 epoch 160, RMSE 2.472

In [10]:
# => epoch 1180 부터 기울기와 절편이 일정하게 출력
# => y = 1.77x1 + 2.4x2 + 77.9
# 학습량 0.1 - RMSE 1.837, 기울기1 1.770, 기울기2 2.408, 절편 77.903
# 학습량 0.5 - RMSE 9.185 기울기1 2.863, 기울기2 2.904, 절편 78.087
# 학습럅 0.05 - RMSE 0.919, 기울기1 1.630, 기울기2 2.345, 절편 77.879

### Keras 

In [11]:
import numpy as np

In [12]:
xdata = np.array([x[:2] for x in data])
ydata = np.array([x[2] for x in data])

In [13]:
model = Sequential()
model.add(Dense(1, input_dim=2, activation='linear'))

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [14]:
model.compile(loss='mse', optimizer='sgd',
              metrics=['accuracy'])

In [15]:
model.fit(xdata, ydata, epochs=1000, verbose=0)

In [16]:
# 기울기
model.get_weights()[0][0],model.get_weights()[0][1]

(array([1.9585477], dtype=float32), array([2.44404], dtype=float32))

In [17]:
# 절편
model.get_weights()[1]

array([74.708755], dtype=float32)

In [18]:
print('기울기1 %.3f' % model.get_weights()[0][0])
print('기울기2 %.3f' % model.get_weights()[0][1])
print('절편 %.3f' % model.get_weights()[1])

기울기1 1.959
기울기2 2.444
절편 74.709


### 학습된 모델 저장과 재사용
* 학습이 끝난후 테스트 결과가 만족스러울때 이를 파일로 저장해두면 새로운 데이터에 바로 사용 가능

In [19]:
# pip install np_utils

In [20]:
import pandas as pd
from tensorflow.keras import utils
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.models import load_model

In [21]:
iris = pd.read_csv('iris.csv', header=None)

x_data = iris.iloc[:, 0:4]
y_data = iris.iloc[:, 4]


le = LabelEncoder()
le.fit(y_data)
y_data = le.transform(y_data)
y_data = utils.to_categorical(y_data)

In [22]:
seed = 211203
np.random.seed(seed)
tf.set_random_seed(seed)

In [23]:
# 신경망, 손실함수, 옵티마이저 설정
model = Sequential()
model.add(Dense(10, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy', 'mse'])

In [24]:
model.fit(x_data, y_data, epochs=100, verbose=0)

In [25]:
print('%.4f' % model.evaluate(x_data, y_data)[1])

150/150 [==============================] - 0s 3ms/sample - loss: 0.4613 - acc: 0.6800 - mean_squared_error: 0.1006
0.6800


In [26]:
# 모델 저장 : 객체.save(경로) 확장자는 h5
model.save('models/iris.h5')

In [27]:
# 모델 불러오기 
models = load_model('models/iris.h5')

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [28]:
print('%.4f' % model.evaluate(x_data, y_data)[1])

150/150 [==============================] - 0s 355us/sample - loss: 0.4613 - acc: 0.6800 - mean_squared_error: 0.1006
0.6800


In [29]:
new_x = np.array([[6.4, 2.7, 5.3, 1.9]])
y_predict = model.predict(new_x)
print(y_predict[0][0],y_predict[0][1],y_predict[0][2])

0.0061044074 0.41117972 0.58271587


### 과적합 문제 해결
* 1998년 존스홉킨스 대학 세즈노프스키 교수가 힐튼 교수가 발표한 역전파 알고리즘에 과심을 가짐
* 즉, 은닉층과 역전파의 효과가 얼마나 큰지 궁금

### 따라서, 광석과 일반돌에 음파를 쏘아 측정치 조사
* 과연 이 돌을 잘 분류할 수 있을지 실험(sonar.csv)

* 논문결과 : 은닉층의 수가 올라갈수록 데이터 예측 정확도도 같이 상승
    + 학습/검증 데이터로 분리해서 진행하면 
    + 학습 예측 정확도는 여전히 증가하지만
    + 증가속도가 다소 지연됨<br><br>
   

* 과적합 방지 방법 - 데이터를 train/test로 분리해서 훈련 실시 (+ 교차검증)

In [30]:
# 측정치 데이터 불러오기
sonar = pd.read_csv('sonar.csv')
sonar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207 entries, 0 to 206
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0.0200  207 non-null    float64
 1   0.0371  207 non-null    float64
 2   0.0428  207 non-null    float64
 3   0.0207  207 non-null    float64
 4   0.0954  207 non-null    float64
 5   0.0986  207 non-null    float64
 6   0.1539  207 non-null    float64
 7   0.1601  207 non-null    float64
 8   0.3109  207 non-null    float64
 9   0.2111  207 non-null    float64
 10  0.1609  207 non-null    float64
 11  0.1582  207 non-null    float64
 12  0.2238  207 non-null    float64
 13  0.0645  207 non-null    float64
 14  0.0660  207 non-null    float64
 15  0.2273  207 non-null    float64
 16  0.3100  207 non-null    float64
 17  0.2999  207 non-null    float64
 18  0.5078  207 non-null    float64
 19  0.4797  207 non-null    float64
 20  0.5783  207 non-null    float64
 21  0.5071  207 non-null    float64
 22  0.

In [31]:
x_data = sonar.iloc[:, 0:60]
y_data = sonar.iloc[:, 60]
print(y_data[:5]) # R(rock) M(mine)

0    R
1    R
2    R
3    R
4    R
Name: R, dtype: object


In [32]:
# 전처리 수행 - 범주형 데이터 변환

le = LabelEncoder()
y_data = le.fit_transform(y_data)
print(y_data[:5])

[1 1 1 1 1]


In [33]:
# 난수 지정
seed = 190121
np.random.seed(seed)
tf.set_random_seed(seed)

In [34]:
# 신경망 구성 :
# 특성수 : 60
# 입력노드 :
# 활성화 함수 : relu
# 최종 출력노드 : 1, 활섬화함수 : sigmoid
model = Sequential()
model.add(Dense(25, input_dim=60, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [35]:
# # 손실함수, 최적화함수 정의
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy','mse'])

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [46]:
model.fit(x_data, y_data, epochs=1000, verbose=0)

In [47]:
print(model.evaluate(x_data, y_data)[1])

207/207 [==============================] - 0s 536us/sample - loss: 0.0075 - acc: 1.0000 - mean_squared_error: 2.7479e-04
1.0


In [48]:
from sklearn.model_selection import train_test_split
# 과적합을 방지하기 위해
# 데이터셋에서 train/test 데이터로 분리
xtrain, xtest, ytrain, ytest = \
     train_test_split(x_data, y_data,
                      test_size=0.3,
                      random_state=seed)

model.fit(xtrain, ytrain, epochs=1000, verbose=0)

print(model.evaluate(xtest, ytest)[1])

63/63 [==============================] - 0s 323us/sample - loss: 0.0399 - acc: 0.9841 - mean_squared_error: 0.0109
0.984127


In [41]:
# 모델 저장 
model.save('models/sonar.csv')

UnicodeDecodeError: 'cp949' codec can't decode byte 0xff in position 32: illegal multibyte sequence